import useTranslation from "next-translate/useTranslation";

const getNationalities = () => {
  const { t } = useTranslation("nationalities");

  return [
    { countryCode: "AF", nationality: t("Afghan") },
    { countryCode: "AL", nationality: t("Albanian") },
    { countryCode: "DZ", nationality: t("Algerian") },
    { countryCode: "US", nationality: t("American") },
    { countryCode: "AD", nationality: t("Andorran") },
    { countryCode: "AO", nationality: t("Angolan") },
    { countryCode: "AM", nationality: t("Armenian") },
    { countryCode: "AT", nationality: t("Austrian") },
    { countryCode: "AZ", nationality: t("Azerbaijani") },
    { countryCode: "AR", nationality: t("Argentinean") },
    { countryCode: "AU", nationality: t("Australian") },
    { countryCode: "BH", nationality: t("Bahraini") },
    { countryCode: "BD", nationality: t("Bangladeshi") },
    { countryCode: "BB", nationality: t("Barbadian") },
    { countryCode: "BY", nationality: t("Belarusian") },
    { countryCode: "BZ", nationality: t("Belizean") },
    { countryCode: "BJ", nationality: t("Beninese") },
    { countryCode: "BM", nationality: t("Bermudian") },
    { countryCode: "BT", nationality: t("Bhutanese") },
    { countryCode: "BO", nationality: t("Bolivian") },
    { countryCode: "BA", nationality: t("Bosnian") },
    { countryCode: "BW", nationality: t("Botswanan") },
    { countryCode: "GB", nationality: t("British") },
    { countryCode: "BG", nationality: t("Bulgarian") },
    { countryCode: "BF", nationality: t("Burkinese") },
    { countryCode: "BI", nationality: t("Burundian") },
    { countryCode: "CA", nationality: t("Canadian") },
    { countryCode: "CN", nationality: t("Chinese") },
    { countryCode: "CO", nationality: t("Colombian") },
    { countryCode: "CU", nationality: t("Cuban") },
    { countryCode: "KH", nationality: t("Cambodian") },
    { countryCode: "CM", nationality: t("Cameroonian") },
    { countryCode: "CV", nationality: t("Cape Verdean") },
    { countryCode: "TD", nationality: t("Chadian") },
    { countryCode: "CL", nationality: t("Chilean") },
    { countryCode: "CG", nationality: t("Congolese") },
    { countryCode: "CR", nationality: t("Costa Rican") },
    { countryCode: "HR", nationality: t("Croatian") },
    { countryCode: "CY", nationality: t("Cypriot") },
    { countryCode: "CZ", nationality: t("Czech") },
    { countryCode: "DK", nationality: t("Danish") },
    { countryCode: "DO", nationality: t("Dominican") },
    { countryCode: "DJ", nationality: t("Djiboutian") },
    { countryCode: "DM", nationality: t("Dominican") },
    { countryCode: "NL", nationality: t("Dutch") },
    { countryCode: "EC", nationality: t("Ecuadorean") },
    { countryCode: "EG", nationality: t("Egyptian") },
    { countryCode: "ER", nationality: t("Eritrean") },
    { countryCode: "EE", nationality: t("Estonian") },
    { countryCode: "ET", nationality: t("Ethiopian") },
    { countryCode: "FJ", nationality: t("Fijian") },
    { countryCode: "FI", nationality: t("Finnish") },
    { countryCode: "PF", nationality: t("French Polynesian") },
    { countryCode: "FR", nationality: t("French") },
    { countryCode: "GA", nationality: t("Gabonese") },
    { countryCode: "GM", nationality: t("Gambian") },
    { countryCode: "GE", nationality: t("Georgian") },
    { countryCode: "DE", nationality: t("German") },
    { countryCode: "GT", nationality: t("Guatemalan") },
    { countryCode: "GH", nationality: t("Ghanaian") },
    { countryCode: "GR", nationality: t("Greek") },
    { countryCode: "GD", nationality: t("Grenadian") },
    { countryCode: "GN", nationality: t("Guinean") },
    { countryCode: "GY", nationality: t("Guyanese") },
    { countryCode: "HT", nationality: t("Haitian") },
    { countryCode: "HN", nationality: t("Honduran") },
    { countryCode: "HU", nationality: t("Hungarian") },
    { countryCode: "IN", nationality: t("Indian") },
    { countryCode: "IE", nationality: t("Irish") },
    { countryCode: "IT", nationality: t("Italian") },
    { countryCode: "IS", nationality: t("Icelander") },
    { countryCode: "ID", nationality: t("Indonesian") },
    { countryCode: "IR", nationality: t("Iranian") },
    { countryCode: "IQ", nationality: t("Iraqi") },
    { countryCode: "JP", nationality: t("Japanese") },
    { countryCode: "JM", nationality: t("Jamaican") },
    { countryCode: "JO", nationality: t("Jordanian") },
    { countryCode: "KZ", nationality: t("Kazakhstani") },
    { countryCode: "KE", nationality: t("Kenyan") },
    { countryCode: "KP", nationality: t("North Korean") },
    { countryCode: "KW", nationality: t("Kuwaiti") },
    { countryCode: "LV", nationality: t("Latvian") },
    { countryCode: "LB", nationality: t("Lebanese") },
    { countryCode: "LR", nationality: t("Liberian") },
    { countryCode: "LY", nationality: t("Libyan") },
    { countryCode: "LT", nationality: t("Lithuanian") },
    { countryCode: "LU", nationality: t("Luxembourger") },
    { countryCode: "MG", nationality: t("Madagascan") },
    { countryCode: "MW", nationality: t("Malawian") },
    { countryCode: "MY", nationality: t("Malaysian") },
    { countryCode: "MV", nationality: t("Maldivian") },
    { countryCode: "ML", nationality: t("Malian") },
    { countryCode: "MT", nationality: t("Maltese") },
    { countryCode: "MR", nationality: t("Mauritanian") },
    { countryCode: "MU", nationality: t("Mauritian") },
    { countryCode: "MC", nationality: t("Monacan") },
    { countryCode: "MN", nationality: t("Mongolian") },
    { countryCode: "ME", nationality: t("Montenegrin") },
    { countryCode: "MA", nationality: t("Moroccan") },
    { countryCode: "MZ", nationality: t("Mozambican") },
    { countryCode: "MX", nationality: t("Mexican") },
    { countryCode: "NA", nationality: t("Namibian") },
    { countryCode: "NP", nationality: t("Nepalese") },
    { countryCode: "NZ", nationality: t("New Zealander") },
    { countryCode: "NI", nationality: t("Nicaraguan") },
    { countryCode: "NE", nationality: t("Nigerien") },
    { countryCode: "NG", nationality: t("Nigerian") },
    { countryCode: "NO", nationality: t("Norwegian") },
    { countryCode: "OM", nationality: t("Omani") },
    { countryCode: "PK", nationality: t("Pakistani") },
    { countryCode: "PW", nationality: t("Palauan") },
    { countryCode: "PS", nationality: t("Palestinian") },
    { countryCode: "PA", nationality: t("Panamanian") },
    { countryCode: "PG", nationality: t("Guinean") },
    { countryCode: "PY", nationality: t("Paraguayan") },
    { countryCode: "PE", nationality: t("Peruvian") },
    { countryCode: "PH", nationality: t("Filipino") },
    { countryCode: "PL", nationality: t("Polish") },
    { countryCode: "PT", nationality: t("Portuguese") },
    { countryCode: "QA", nationality: t("Qatari") },
    { countryCode: "RO", nationality: t("Romanian") },
    { countryCode: "RW", nationality: t("Rwandan") },
    { countryCode: "SV", nationality: t("Salvadoran") },
    { countryCode: "AS", nationality: t("Samoan") },
    { countryCode: "SA", nationality: t("Saudi Arabian") },
    { countryCode: "SN", nationality: t("Senegalese") },
    { countryCode: "RS", nationality: t("Serbian") },
    { countryCode: "SL", nationality: t("Sierra Leonean") },
    { countryCode: "SG", nationality: t("Singaporean") },
    { countryCode: "SK", nationality: t("Slovak") },
    { countryCode: "SI", nationality: t("Slovenian") },
    { countryCode: "SB", nationality: t("Solomon Islander") },
    { countryCode: "SO", nationality: t("Somali") },
    { countryCode: "ZA", nationality: t("South African") },
    { countryCode: "KR", nationality: t("South Korean") },
    { countryCode: "ES", nationality: t("Spanish") },
    { countryCode: "SE", nationality: t("Swedish") },
    { countryCode: "CH", nationality: t("Swiss") },
    { countryCode: "SY", nationality: t("Syrian") },
    { countryCode: "LK", nationality: t("Sri Lankan") },
    { countryCode: "SD", nationality: t("Sudanese") },
    { countryCode: "SR", nationality: t("Surinamese") },
    { countryCode: "SZ", nationality: t("Swazi") },
    { countryCode: "TW", nationality: t("Taiwanese") },
    { countryCode: "TJ", nationality: t("Tajik") },
    { countryCode: "TH", nationality: t("Thai") },
    { countryCode: "TG", nationality: t("Togolese") },
    { countryCode: "TT", nationality: t("Trinidadian") },
    { countryCode: "TN", nationality: t("Tunisian") },
    { countryCode: "TR", nationality: t("Turkish") },
    { countryCode: "TM", nationality: t("Turkmenian") },
    { countryCode: "TV", nationality: t("Tuvaluan") },
    { countryCode: "UG", nationality: t("Ugandan") },
    { countryCode: "UA", nationality: t("Ukrainian") },
    { countryCode: "AE", nationality: t("Emirati") },
    { countryCode: "VE", nationality: t("Venezuelan") },
    { countryCode: "VN", nationality: t("Vietnamese") },
    { countryCode: "UY", nationality: t("Uruguayan") },
    { countryCode: "UZ", nationality: t("Uzbek") },
    { countryCode: "VU", nationality: t("Ni-Vanuatu") },
    { countryCode: "YE", nationality: t("Yemenite") },
    { countryCode: "ZM", nationality: t("Zambian") },
  ];
};

export default getNationalities;
